version: '2'
services:
  deadly-wish:
    build: .
    environment:
      - DISPLAY=localhost:0
      - XAUTHORITY=$XAUTHORITY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/shm:/dev/shm
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
      - /dev/video0:/dev/video0
      - /dev/input:/dev/input
      - /etc/localtime:/etc/localtime
